# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: template-index


  assets:
    cmds:
      - cp -r ./assets ./generates/assets

  template-index:
    env:
      FILE: index.html
    cmds:
      - sh ./scripts/docker-template.sh

  template-consulting:
    env:
      FILE: consulting.html
    cmds:
      - sh ./scripts/docker-template.sh
