# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: template-index


  assets:
    cmds:
      - cp -r ./assets ./generates/assets

  template-index:
    aliases: ['ti']
    env:
      FILE: index.html
    cmds:
      - sh ./scripts/docker-template.sh
  template-srv:
    aliases: ['ts']
    env:
      FILE: server-solutions.html
    cmds:
      - sh ./scripts/docker-template.sh
